export const GET_SELECTED_CHAR_ID = "GET_SELECTED_CHAR_ID";
export const FETCH_RESIDENT_CHARACTERS = "FETCH_RESIDENT_CHARACTERS";
export const CLEAR_RESIDENT_CHARACTERS = "CLEAR_RESIDENT_CHARACTERS";
